version: '2'
services:
  backend:
    build: backend
    volumes:
      - ./locator-db:/app/locator-db
    pids_limit: 100
    restart: always
  frontend:
    build: frontend
    ports:
      - "3:80"
    restart: always